Description: For an unkown reason, _() is undefine in keystone/exception.py and FTBFS
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2013-09-13

Index: keystone/keystone/exception.py
===================================================================
--- keystone.orig/keystone/exception.py	2014-02-14 09:58:24.000000000 +0800
+++ keystone/keystone/exception.py	2014-02-14 09:58:31.000000000 +0800
@@ -27,6 +27,8 @@
 # Tests use this to make exception message format errors fatal
 _FATAL_EXCEPTION_FORMAT_ERRORS = False
 
+def _(a):
+ return a
 
 class Error(StandardError):
     """Base error class.
