# Russian (Russia) translations for keystone.
# Copyright (C) 2013 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-03-02 06:00+0000\n"
"PO-Revision-Date: 2013-07-29 22:01+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Russian (Russia) "
"(http://www.transifex.com/projects/p/openstack/language/ru_RU/)\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:23
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/clean.py:25
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/clean.py:30
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/clean.py:39
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/cli.py:80 keystone/cli.py:118
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/exception.py:48
msgid "missing exception kwargs (programmer error)"
msgstr ""

#: keystone/exception.py:78
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s. The server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:87
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:96
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:102
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:112
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:131
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:137
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:145
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:153
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:161
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:168
#, python-format
msgid "You are not authorized to perform the requested action, %(action)s."
msgstr ""

#: keystone/exception.py:173
#, python-format
msgid "Could not change immutable attribute %(attribute)s in target %(target)s"
msgstr ""

#: keystone/exception.py:178
#, python-format
msgid "Could not find, %(target)s."
msgstr ""

#: keystone/exception.py:184
#, python-format
msgid "Could not find endpoint, %(endpoint_id)s."
msgstr ""

#: keystone/exception.py:191
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:196
#, python-format
msgid "Could not find policy, %(policy_id)s."
msgstr ""

#: keystone/exception.py:200
#, python-format
msgid "Could not find role, %(role_id)s."
msgstr ""

#: keystone/exception.py:204
#, python-format
msgid "Could not find region, %(region_id)s."
msgstr ""

#: keystone/exception.py:208
#, python-format
msgid "Could not find service, %(service_id)s."
msgstr ""

#: keystone/exception.py:212
#, python-format
msgid "Could not find domain, %(domain_id)s."
msgstr ""

#: keystone/exception.py:216
#, python-format
msgid "Could not find project, %(project_id)s."
msgstr ""

#: keystone/exception.py:220
#, python-format
msgid "Could not find token, %(token_id)s."
msgstr ""

#: keystone/exception.py:224
#, python-format
msgid "Could not find user, %(user_id)s."
msgstr ""

#: keystone/exception.py:228
#, python-format
msgid "Could not find group, %(group_id)s."
msgstr ""

#: keystone/exception.py:232
#, python-format
msgid "Could not find mapping, %(mapping_id)s."
msgstr ""

#: keystone/exception.py:236
#, python-format
msgid "Could not find trust, %(trust_id)s."
msgstr ""

#: keystone/exception.py:240
#, python-format
msgid "Could not find credential, %(credential_id)s."
msgstr ""

#: keystone/exception.py:244
#, python-format
msgid "Could not find version, %(version)s."
msgstr ""

#: keystone/exception.py:248
#, python-format
msgid "Could not find IdentityProvider, %(idp_id)s."
msgstr ""

#: keystone/exception.py:252
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for IdentityProvider, "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:257
#, python-format
msgid "Conflict occurred attempting to store %(type)s. %(details)s"
msgstr ""

#: keystone/exception.py:264
msgid "Request is too large."
msgstr ""

#: keystone/exception.py:270
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request. "
"%(exception)s"
msgstr ""

#: keystone/exception.py:277
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:282
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:287
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:294
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:300
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/notifications.py:119
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:128
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/notifications.py:136
#, python-format
msgid "Callback: `%(callback)s` subscribed to event `%(event)s`."
msgstr ""

#: keystone/notifications.py:155
#, python-format
msgid ""
"Invoking callback %(cb_name)s for event %(service)s %(resource_type)s "
"%(operation)s for%(payload)s"
msgstr ""

#: keystone/notifications.py:218
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:289
#, python-format
msgid "CADF Event: %s"
msgstr ""

#: keystone/notifications.py:302
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:71
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: keystone/assignment/controllers.py:105
#: keystone/assignment/controllers.py:219 keystone/identity/controllers.py:129
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:142
#, python-format
msgid "User %(user_id)s in project %(project_id)s doesn't exist."
msgstr ""

#: keystone/assignment/controllers.py:160
msgid "Marker could not be found"
msgstr ""

#: keystone/assignment/controllers.py:171
msgid "Invalid limit value"
msgstr ""

#: keystone/assignment/controllers.py:473
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:478
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:691
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""

#: keystone/assignment/core.py:240
#, python-format
msgid "Creating the default role %s because it does not exist."
msgstr ""

#: keystone/assignment/core.py:268
#, python-format
msgid "Removing role %s failed because it does not exist."
msgstr ""

#: keystone/assignment/core.py:330
msgid "delete the default domain"
msgstr ""

#: keystone/assignment/core.py:341
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/assignment/core.py:378
#, python-format
msgid ""
"Project %(projectid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:391
#, python-format
msgid ""
"Group %(groupid)s not found when deleting domain contents for "
"%(domainid)s, continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:403
#, python-format
msgid ""
"User %(userid)s not found when deleting domain contents for %(domainid)s,"
" continuing with cleanup."
msgstr ""

#: keystone/assignment/core.py:501
#, python-format
msgid "Group %s not found, no tokens to invalidate."
msgstr ""

#: keystone/assignment/core.py:539
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:541
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:543
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/core.py:544
#, python-format
msgid ""
"Group (%(group)s), referenced in assignment for %(target)s, not found - "
"ignoring."
msgstr ""

#: keystone/assignment/core.py:985 keystone/common/controller.py:261
#: keystone/identity/core.py:228
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/assignment/backends/kvs.py:201
#: keystone/assignment/backends/ldap.py:580
#: keystone/assignment/backends/sql.py:351
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/ldap.py:110
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:199
#: keystone/assignment/backends/ldap.py:247 keystone/common/ldap/core.py:331
#: keystone/identity/backends/kvs.py:116 keystone/identity/backends/kvs.py:223
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:207 keystone/common/ldap/core.py:321
#: keystone/identity/backends/kvs.py:124 keystone/identity/backends/kvs.py:151
#: keystone/identity/backends/kvs.py:230 keystone/identity/backends/kvs.py:258
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/backends/ldap.py:249
#: keystone/assignment/backends/ldap.py:257
#: keystone/assignment/backends/ldap.py:261
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:314
#: keystone/assignment/backends/sql.py:135
msgid "Inherited roles can only be assigned to domains"
msgstr ""

#: keystone/assignment/backends/ldap.py:553
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:559
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/ldap.py:666
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/assignment/backends/sql.py:122
#, python-format
msgid ""
"Unexpected combination of grant attributes - User, Group, Project, "
"Domain: %s"
msgstr ""

#: keystone/assignment/backends/sql.py:291
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/backends/sql.py:372
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/auth/controllers.py:56
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:64
#, python-format
msgid "Driver requested method %(req)s does not match plugin name %(plugin)s."
msgstr ""

#: keystone/auth/controllers.py:69
#, python-format
msgid "Auth Plugin %s does not have a \"method\" attribute."
msgstr ""

#: keystone/auth/controllers.py:73
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:114
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:120 keystone/auth/plugins/password.py:40
#: keystone/token/core.py:79 keystone/token/core.py:95
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/auth/controllers.py:277
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:280
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:283
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:375
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:382
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:391
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:422
msgid "User not found"
msgstr ""

#: keystone/auth/plugins/external.py:45
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:55
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/oauth1.py:54
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:68
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:46 keystone/token/core.py:71
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/auth/plugins/password.py:122
msgid "Invalid username or password"
msgstr ""

#: keystone/auth/plugins/saml2.py:88
msgid "Federation token is expired"
msgstr ""

#: keystone/catalog/core.py:41
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:46
#, python-format
msgid ""
"Malformed endpoint %(url)s - unknown key %(keyerror)s(are you missing "
"brackets ?)"
msgstr ""

#: keystone/catalog/core.py:52
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/catalog/backends/templated.py:105
#, python-format
msgid "Unable to open template file %s"
msgstr ""

#: keystone/common/authorization.py:73
msgid "RBAC: Invalid user data in v3 token"
msgstr ""

#: keystone/common/authorization.py:78
msgid "RBAC: Proceeding without project"
msgstr ""

#: keystone/common/authorization.py:96
msgid "RBAC: Invalid user data in v2 token"
msgstr ""

#: keystone/common/authorization.py:101
msgid "RBAC: Proceeding without tenant"
msgstr ""

#: keystone/common/base64utils.py:203 keystone/common/base64utils.py:276
#: keystone/common/base64utils.py:330
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:209
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:213
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:219
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:238 keystone/common/base64utils.py:259
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:38
#, python-format
msgid "RBAC: Authorizing %(action)s(%(kwargs)s)"
msgstr ""

#: keystone/common/controller.py:45
msgid "RBAC: using auth context from the request environment"
msgstr ""

#: keystone/common/controller.py:50
msgid "RBAC: building auth context from the incoming auth token"
msgstr ""

#: keystone/common/controller.py:54 keystone/middleware/core.py:231
msgid "RBAC: Invalid token"
msgstr ""

#: keystone/common/controller.py:83 keystone/common/controller.py:174
#: keystone/common/controller.py:562
msgid "RBAC: Bypassing authorization"
msgstr ""

#: keystone/common/controller.py:130 keystone/common/controller.py:172
#: keystone/common/controller.py:580
msgid "RBAC: Authorization granted"
msgstr ""

#: keystone/common/controller.py:160
#, python-format
msgid "RBAC: Adding query filter params (%s)"
msgstr ""

#: keystone/common/controller.py:533
msgid "Invalid token in _get_domain_id_for_request"
msgstr ""

#: keystone/common/dependency.py:81
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:86
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:221
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:240
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/serializer.py:201
msgid "Multiple truncation attributes found"
msgstr ""

#: keystone/common/utils.py:76
#, python-format
msgid "Truncating user password to %s characters."
msgstr ""

#: keystone/common/utils.py:194 keystone/credential/controllers.py:41
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/utils.py:273
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/wsgi.py:72
msgid "No bind information present in token"
msgstr ""

#: keystone/common/wsgi.py:76
#, python-format
msgid "Named bind mode %s not in bind information"
msgstr ""

#: keystone/common/wsgi.py:83
msgid "Kerberos credentials required and not present"
msgstr ""

#: keystone/common/wsgi.py:87
msgid "Kerberos credentials do not match those in bind"
msgstr ""

#: keystone/common/wsgi.py:90
msgid "Kerberos bind authentication successful"
msgstr ""

#: keystone/common/wsgi.py:93
#, python-format
msgid "Ignoring unknown bind for permissive mode: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:97
#, python-format
msgid "Couldn't verify unknown bind: {%(bind_type)s: %(identifier)s}"
msgstr ""

#: keystone/common/wsgi.py:186
#, python-format
msgid "arg_dict: %s"
msgstr ""

#: keystone/common/wsgi.py:214
#, python-format
msgid "Authorization failed. %(exception)s from %(remote_addr)s"
msgstr ""

#: keystone/common/wsgi.py:287
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:299
msgid "Invalid token in _get_trust_id_for_request"
msgstr ""

#: keystone/common/wsgi.py:478 keystone/tests/test_wsgi.py:252
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/core.py:53
#, python-format
msgid "CACHE_GET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:59
#, python-format
msgid "CACHE_GET_MULTI: \"%(keys)r\" Values: \"%(values)r\""
msgstr ""

#: keystone/common/cache/core.py:64
#, python-format
msgid "CACHE_SET: Key: \"%(key)r\" Value: \"%(value)r\""
msgstr ""

#: keystone/common/cache/core.py:69
#, python-format
msgid "CACHE_SET_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:74
#, python-format
msgid "CACHE_DELETE: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:77
#, python-format
msgid "CACHE_DELETE_MULTI: \"%r\""
msgstr ""

#: keystone/common/cache/core.py:95
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""

#: keystone/common/cache/core.py:103
#, python-format
msgid "Keystone Cache Config: %s"
msgstr ""

#: keystone/common/cache/core.py:118
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/core.py:151
#, python-format
msgid "Adding cache-proxy '%s' to backend."
msgstr ""

#: keystone/common/cache/backends/mongo.py:230
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:235
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:240
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:251
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:259
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:274
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:300
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:309
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/cache/backends/mongo.py:402
#, python-format
msgid ""
"TTL index already exists on db collection <%(c_name)s>, remove index "
"<%(indx_name)s> first to make updated mongo_ttl_seconds value to be  "
"effective"
msgstr ""

#: keystone/common/environment/__init__.py:51
#, python-format
msgid "Environment configured as: %s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:51
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:122
msgid "Server error"
msgstr ""

#: keystone/common/kvs/core.py:62
#, python-format
msgid "Registering Dogpile Backend %(backend_path)s as %(backend_name)s"
msgstr ""

#: keystone/common/kvs/core.py:70
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:105
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:121
#, python-format
msgid "Importing class %s as KVS proxy."
msgstr ""

#: keystone/common/kvs/core.py:129
#, python-format
msgid "%s is not a dogpile.proxy.ProxyBackend"
msgstr ""

#: keystone/common/kvs/core.py:133
#, python-format
msgid "Adding proxy '%(proxy)s' to KVS %(name)s."
msgstr ""

#: keystone/common/kvs/core.py:140
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:157
#, python-format
msgid ""
"Non-expiring keys not supported/required by %(region)s backend; unable to"
" set key_mangler for backend: %(err)s"
msgstr ""

#: keystone/common/kvs/core.py:183
#, python-format
msgid "Using %(func)s as KVS region %(name)s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:193
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:195
#, python-format
msgid "Using default dogpile sha1_mangle_key as KVS region %s key_mangler"
msgstr ""

#: keystone/common/kvs/core.py:205
#, python-format
msgid "KVS region %s key_mangler disabled."
msgstr ""

#: keystone/common/kvs/core.py:234
#, python-format
msgid "KVS region configuration for %(name)s: %(config)r"
msgstr ""

#: keystone/common/kvs/core.py:347
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:351
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/core.py:375
#, python-format
msgid "KVS lock acquired for: %s"
msgstr ""

#: keystone/common/kvs/core.py:394
#, python-format
msgid "KVS lock released for: %s"
msgstr ""

#: keystone/common/kvs/core.py:396
#, python-format
msgid "KVS lock released (timeout reached) for: %s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:71
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:110
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:181
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:76
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:86
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:98
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:214
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%s\". Format must be "
"<ldap_attribute>:<keystone_attribute>"
msgstr ""

#: keystone/common/ldap/core.py:220
#, python-format
msgid ""
"Invalid additional attribute mapping: \"%(item)s\". Value "
"\"%(attr_map)s\" must use one of %(keys)s."
msgstr ""

#: keystone/common/ldap/core.py:300
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:305
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:310
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:431
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:488
#, python-format
msgid "LDAP init: url=%s"
msgstr ""

#: keystone/common/ldap/core.py:489
#, python-format
msgid ""
"LDAP init: use_tls=%(use_tls)s\n"
"tls_cacertfile=%(tls_cacertfile)s\n"
"tls_cacertdir=%(tls_cacertdir)s\n"
"tls_req_cert=%(tls_req_cert)s\n"
"tls_avail=%(tls_avail)s\n"
msgstr ""

#: keystone/common/ldap/core.py:508
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:512
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:522
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:534
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:541
#, python-format
msgid "LDAP TLS: invalid TLS_REQUIRE_CERT Option=%s"
msgstr ""

#: keystone/common/ldap/core.py:555
#, python-format
msgid "LDAP bind: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:569
#, python-format
msgid "LDAP add: dn=%(dn)s, attrs=%(attrs)s"
msgstr ""

#: keystone/common/ldap/core.py:580
#, python-format
msgid ""
"LDAP search: dn=%(dn)s, scope=%(scope)s, query=%(query)s, "
"attrs=%(attrlist)s"
msgstr ""

#: keystone/common/ldap/core.py:633
msgid ""
"LDAP Server does not support paging. Disable paging in keystone.conf to "
"avoid this message."
msgstr ""

#: keystone/common/ldap/core.py:649
#, python-format
msgid "LDAP modify: dn=%(dn)s, modlist=%(modlist)s"
msgstr ""

#: keystone/common/ldap/core.py:655
#, python-format
msgid "LDAP delete: dn=%s"
msgstr ""

#: keystone/common/ldap/core.py:660
#, python-format
msgid "LDAP delete_ext: dn=%(dn)s, serverctrls=%(serverctrls)s"
msgstr ""

#: keystone/common/sql/core.py:189
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/migration.py:55
#: keystone/openstack/common/db/sqlalchemy/migration.py:191
msgid "version should be an integer"
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:59
#, python-format
msgid ""
"Credential %(access)s already exists with different secret in %(table)s "
"table"
msgstr ""

#: keystone/common/sql/migrate_repo/versions/033_migrate_ec2credentials_table_credentials.py:69
#, python-format
msgid ""
"Credential %(access)s already exists with different project in %(table)s "
"table"
msgstr ""

#: keystone/contrib/ec2/controllers.py:305
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:333
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:54
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/example/core.py:63 keystone/contrib/example/core.py:72
#, python-format
msgid ""
"Received the following notification: service %(service)s, resource_type: "
"%(resource_type)s, operation %(operation)s payload %(payload)s"
msgstr ""

#: keystone/contrib/federation/utils.py:196
msgid "Could not map user"
msgstr ""

#: keystone/contrib/federation/utils.py:225
#, python-format
msgid "Ignoring user name %s"
msgstr ""

#: keystone/contrib/kds/cli/api.py:48
#, python-format
msgid "Serving on http://%(host)s:%(port)d"
msgstr ""

#: keystone/contrib/kds/common/exception.py:24
msgid "An unknown exception occurred"
msgstr ""

#: keystone/contrib/kds/common/exception.py:42
#, python-format
msgid ""
"Failed to load the '%(backend)s' backend because it is not allowed. "
"Allowed backends are: %(allowed)s"
msgstr ""

#: keystone/contrib/kds/common/exception.py:47
#, python-format
msgid "Cannot set key data for %(name)s: %(reason)s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:69
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:142
#: keystone/contrib/oauth1/backends/sql.py:284
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:149
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:192
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:241
#: keystone/contrib/oauth1/controllers.py:311
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:255
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:259
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:263
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:267
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:271
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:327
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:342
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:94
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:198
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:264
msgid "Access token not found"
msgstr ""

#: keystone/credential/core.py:119
#, python-format
msgid "Deletion of credential is not required: %s"
msgstr ""

#: keystone/identity/controllers.py:132
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/identity/controllers.py:159
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/controllers.py:200
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr ""

#: keystone/identity/controllers.py:219
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr ""

#: keystone/identity/core.py:104
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""

#: keystone/identity/core.py:128
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/identity/core.py:141
#, python-format
msgid "Ignoring file (%s) while scanning domain config directory"
msgstr ""

#: keystone/identity/core.py:182
msgid ""
"Running an experimental and unsupported configuration "
"(domain_specific_drivers_enabled = True); this will result in known "
"issues."
msgstr ""

#: keystone/identity/backends/kvs.py:71 keystone/identity/backends/kvs.py:73
#: keystone/identity/backends/ldap.py:56 keystone/identity/backends/ldap.py:58
#: keystone/identity/backends/ldap.py:64 keystone/identity/backends/ldap.py:66
#: keystone/identity/backends/pam.py:48 keystone/identity/backends/pam.py:65
#: keystone/identity/backends/sql.py:111 keystone/identity/backends/sql.py:113
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/backends/kvs.py:177 keystone/identity/backends/kvs.py:186
#: keystone/identity/backends/sql.py:197 keystone/identity/backends/sql.py:208
msgid "User not found in group"
msgstr ""

#: keystone/identity/backends/ldap.py:95 keystone/identity/backends/sql.py:159
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:98
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:166
#, python-format
msgid ""
"Group member '%(user_dn)s' not found in '%(group_id)s'. The user should "
"be removed from the group. The user will be ignored."
msgstr ""

#: keystone/identity/backends/ldap.py:307
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/middleware/core.py:236
msgid "Auth token not in the request header. Will not build auth context."
msgstr ""

#: keystone/middleware/core.py:241
msgid "Auth context already exists in the request environment"
msgstr ""

#: keystone/middleware/core.py:246
#, python-format
msgid "RBAC: auth_context: %s"
msgstr ""

#: keystone/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: keystone/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr ""

#: keystone/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: keystone/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: keystone/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: keystone/openstack/common/gettextutils.py:252
msgid "Message objects do not support addition."
msgstr ""

#: keystone/openstack/common/gettextutils.py:261
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: keystone/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: keystone/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: keystone/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: keystone/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: keystone/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: keystone/openstack/common/log.py:301
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: keystone/openstack/common/log.py:404
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: keystone/openstack/common/log.py:455
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: keystone/openstack/common/log.py:625
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: keystone/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: keystone/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: keystone/openstack/common/loopingcall.py:129
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: keystone/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: keystone/openstack/common/policy.py:75
msgid "JSON file containing policy"
msgstr ""

#: keystone/openstack/common/policy.py:78
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: keystone/openstack/common/policy.py:92
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: keystone/openstack/common/policy.py:182
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: keystone/openstack/common/policy.py:212
msgid "Rules successfully reloaded"
msgstr ""

#: keystone/openstack/common/policy.py:258
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: keystone/openstack/common/policy.py:273
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: keystone/openstack/common/policy.py:481
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: keystone/openstack/common/policy.py:491
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: keystone/openstack/common/policy.py:761
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: keystone/openstack/common/processutils.py:130
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: keystone/openstack/common/processutils.py:145
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:169
#: keystone/openstack/common/processutils.py:241
#, python-format
msgid "Result was %s"
msgstr ""

#: keystone/openstack/common/processutils.py:181
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: keystone/openstack/common/processutils.py:220
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:222
msgid "Environment not supported over SSH"
msgstr ""

#: keystone/openstack/common/processutils.py:226
msgid "process_input not supported over SSH"
msgstr ""

#: keystone/openstack/common/service.py:134
#: keystone/openstack/common/service.py:346
msgid "Full set of CONF:"
msgstr ""

#: keystone/openstack/common/service.py:143
#: keystone/openstack/common/service.py:231
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: keystone/openstack/common/service.py:155
msgid "Exception during rpc cleanup."
msgstr ""

#: keystone/openstack/common/service.py:200
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: keystone/openstack/common/service.py:237
msgid "Unhandled exception"
msgstr ""

#: keystone/openstack/common/service.py:270
msgid "Forking too fast, sleeping"
msgstr ""

#: keystone/openstack/common/service.py:289
#, python-format
msgid "Started child %d"
msgstr ""

#: keystone/openstack/common/service.py:299
#, python-format
msgid "Starting %d workers"
msgstr ""

#: keystone/openstack/common/service.py:316
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: keystone/openstack/common/service.py:320
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: keystone/openstack/common/service.py:324
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: keystone/openstack/common/service.py:354
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: keystone/openstack/common/service.py:372
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: keystone/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: keystone/openstack/common/sslutils.py:59
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: keystone/openstack/common/sslutils.py:98
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: keystone/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: keystone/openstack/common/strutils.py:188
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: keystone/openstack/common/strutils.py:195
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: keystone/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: keystone/openstack/common/crypto/utils.py:27
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: keystone/openstack/common/crypto/utils.py:34
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: keystone/openstack/common/crypto/utils.py:43
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: keystone/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/migration.py:221
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:615
msgid "DB exception wrapped."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:684
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:764
msgid ""
"This application has not enabled MySQL traditional mode, which means "
"silent data corruption may occur. Please encourage the application "
"developers to enable this mode."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/session.py:789
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/test_migrations.py:103
#, python-format
msgid "Got lock \"%s\""
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/test_migrations.py:106
#, python-format
msgid "Lock released \"%s\""
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:194
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:200
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:280
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: keystone/openstack/common/db/sqlalchemy/utils.py:301
msgid "Unsupported id columns type"
msgstr ""

#: keystone/policy/backends/rules.py:98
#, python-format
msgid "enforce %(action)s: %(credentials)s"
msgstr ""

#: keystone/tests/core.py:146
#, python-format
msgid "Failed to checkout %s"
msgstr ""

#: keystone/tests/fakeldap.py:249
#, python-format
msgid "FakeLdap delete item: dn=%s"
msgstr ""

#: keystone/token/controllers.py:359
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:376 keystone/token/controllers.py:379
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/core.py:86
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:85
msgid ""
"keystone.conf [signing] token_format (deprecated) conflicts with "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:93
msgid ""
"keystone.conf [signing] token_format is deprecated in favor of "
"keystone.conf [token] provider"
msgstr ""

#: keystone/token/provider.py:103
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""

#: keystone/token/provider.py:194
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/provider.py:197
msgid "The token is malformed or expired."
msgstr ""

#: keystone/token/backends/kvs.py:55
msgid ""
"It is recommended to only use the base key-value-store implementation for"
" the token driver for testing purposes.  Please use "
"keystone.token.backends.memcache.Token or "
"keystone.token.backends.sql.Token instead."
msgstr ""

#: keystone/token/backends/kvs.py:130
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/backends/kvs.py:169
#, python-format
msgid "Token `%(token_id)s` is expired, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:178
#, python-format
msgid "Token `%(token_id)s` is revoked, removing from `%(user_key)s`."
msgstr ""

#: keystone/token/backends/kvs.py:203
#, python-format
msgid "Token `%s` is expired, not adding to the revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:223
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/backends/kvs.py:237
#, python-format
msgid ""
"Removing `%s` from revocation list due to invalid expires data in "
"revocation list."
msgstr ""

#: keystone/token/backends/kvs.py:268
#, python-format
msgid ""
"Invalid token entry expected tuple of `(<token_id>, <expires>)` got: "
"`%(item)r`"
msgstr ""

#: keystone/token/backends/kvs.py:277
#, python-format
msgid "Invalid expires time on token `%(token_id)s`: %(expires)r"
msgstr ""

#: keystone/token/providers/common.py:182
#: keystone/token/providers/common.py:285
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:187
#: keystone/token/providers/common.py:290
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:212
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:276
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:340
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:435
msgid "Oauth is disabled."
msgstr ""

#: keystone/token/providers/common.py:536
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:544
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/common.py:611
#: keystone/token/providers/common.py:621
msgid "Failed to validate token"
msgstr ""

#: keystone/token/providers/pki.py:41
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:42
msgid "Unable to sign token."
msgstr ""

#~ msgid "Unable to locate specified logging config file: %s"
#~ msgstr ""

#~ msgid "Invalid syslog facility"
#~ msgstr ""

#~ msgid "Invalid token in normalize_domain_id"
#~ msgstr ""

#~ msgid "Cannot migrate EC2 credential: %s"
#~ msgstr ""

#~ msgid "Create tenant %s"
#~ msgstr ""

#~ msgid "Create user %s"
#~ msgstr ""

#~ msgid "Add user %(user_id)s to tenant %(tenant_id)s"
#~ msgstr ""

#~ msgid "Ignoring existing role %s"
#~ msgstr ""

#~ msgid "Create role %s"
#~ msgstr ""

#~ msgid "Assign role %(role_id)s to user %(user_id)s on tenant %(tenant_id)s"
#~ msgstr ""

#~ msgid "Creating ec2 cred for user %(user_id)s and tenant %(tenant_id)s"
#~ msgstr ""

#~ msgid "Changing Name not supported by LDAP"
#~ msgstr ""

#~ msgid "Failed to verify token"
#~ msgstr ""

#~ msgid "CACHE_GET: Key: \"%(key)s)\" \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_GET_MULTI: \"%(key)s\" \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_SET: Key: %(key)s Value: %(value)s"
#~ msgstr ""

#~ msgid "CACHE_SET_MULTI: %s"
#~ msgstr ""

#~ msgid "CACHE_DELETE: %s"
#~ msgstr ""

#~ msgid "CACHE_DELETE_MULTI: %s"
#~ msgstr ""

#~ msgid "Invalid LDAP TLS certs option: %(option). Choose one of: %(options)s"
#~ msgstr ""

#~ msgid "Non-oauth parameter - roles, do not match"
#~ msgstr ""

#~ msgid "could not find matching roles for provided role ids"
#~ msgstr ""

#~ msgid "Failed to understand rule %(rule)s"
#~ msgstr ""

#~ msgid "Failed to understand rule %(rule)r"
#~ msgstr ""

#~ msgid ""
#~ msgstr ""

#~ msgid "CACHE_GET: Key: \"%(key)s\" Value: \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_GET_MULTI: \"%(keys)s\" Values: \"%(values)s\""
#~ msgstr ""

#~ msgid "CACHE_SET: Key: \"%(key)s\" Value: \"%(value)s\""
#~ msgstr ""

#~ msgid "CACHE_SET_MULTI: \"%s\""
#~ msgstr ""

#~ msgid "CACHE_DELETE: \"%s\""
#~ msgstr ""

#~ msgid "CACHE_DELETE_MULTI: \"%s\""
#~ msgstr ""

#~ msgid "Global engine callback raised."
#~ msgstr ""

#~ msgid "MySQL server has gone away: %s"
#~ msgstr ""

#~ msgid "DB2 server has gone away: %s"
#~ msgstr ""

#~ msgid "Got mysql server has gone away: %s"
#~ msgstr ""

#~ msgid "This extension does not provide migrations."
#~ msgstr ""

#~ msgid ""
#~ "keystone.auth.external.ExternalDefault is deprecated "
#~ "infavor of keystone.auth.external.Default"
#~ msgstr ""

#~ msgid ""
#~ "keystone.auth.external.ExternalDomain is deprecated "
#~ "infavor of keystone.auth.external.Domain"
#~ msgstr ""

#~ msgid "Verify error: %s"
#~ msgstr ""

#~ msgid ""
#~ "Signing error: Unable to load "
#~ "certificate - ensure you've configured "
#~ "PKI with 'keystone-manage pki_setup'"
#~ msgstr ""

#~ msgid "Signing error: %s"
#~ msgstr ""

#~ msgid "RBAC: Invalid user"
#~ msgstr ""

#~ msgid "Maximum lock attempts on %s occured."
#~ msgstr ""

#~ msgid "Backend `%s` is not a valid dogpile memcached backend."
#~ msgstr ""

#~ msgid "Invalid LDAP deref option: %s. Choose one of: "
#~ msgstr ""

#~ msgid "Non-oauth parameter - project, do not match"
#~ msgstr ""

#~ msgid "Upgrade DB using Essex release first."
#~ msgstr ""

#~ msgid "%s not in valid priorities"
#~ msgstr ""

#~ msgid ""
#~ "Problem '%(e)s' attempting to send to"
#~ " notification system. Payload=%(payload)s"
#~ msgstr ""

#~ msgid "Failed to load notifier %s. These notifications will not be sent."
#~ msgstr ""

#~ msgid "Could not send notification to %(topic)s. Payload=%(message)s"
#~ msgstr ""

#~ msgid ""
#~ "A RPC is being made while holding"
#~ " a lock. The locks currently held "
#~ "are %(locks)s. This is probably a "
#~ "bug. Please report it. Include the "
#~ "following: [%(stack)s]."
#~ msgstr ""

#~ msgid "Pool creating new connection"
#~ msgstr ""

#~ msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
#~ msgstr ""

#~ msgid "_call_waiters: %s"
#~ msgstr ""

#~ msgid ""
#~ "Number of call waiters is greater "
#~ "than warning threshold: %d. There could"
#~ " be a MulticallProxyWaiter leak."
#~ msgstr ""

#~ msgid "unpacked context: %s"
#~ msgstr ""

#~ msgid "UNIQUE_ID is %s."
#~ msgstr ""

#~ msgid "received %s"
#~ msgstr ""

#~ msgid "no method for message: %s"
#~ msgstr ""

#~ msgid "No method for message: %s"
#~ msgstr ""

#~ msgid "Expected exception during message handling (%s)"
#~ msgstr ""

#~ msgid "Exception during message handling"
#~ msgstr ""

#~ msgid "Making synchronous call on %s ..."
#~ msgstr ""

#~ msgid "MSG_ID is %s"
#~ msgstr ""

#~ msgid "Making asynchronous cast on %s..."
#~ msgstr ""

#~ msgid "Making asynchronous fanout cast..."
#~ msgstr ""

#~ msgid "Sending %(event_type)s on %(topic)s"
#~ msgstr ""

#~ msgid "An unknown RPC related exception occurred."
#~ msgstr ""

#~ msgid "Exception in string format operation"
#~ msgstr ""

#~ msgid ""
#~ "Remote error: %(exc_type)s %(value)s\n"
#~ "%(traceback)s."
#~ msgstr ""

#~ msgid ""
#~ "Timeout while waiting on RPC response"
#~ " - topic: \"%(topic)s\", RPC method: "
#~ "\"%(method)s\" info: \"%(info)s\""
#~ msgstr ""

#~ msgid "<unknown>"
#~ msgstr ""

#~ msgid "Found duplicate message(%(msg_id)s). Skipping it."
#~ msgstr ""

#~ msgid "Invalid reuse of an RPC connection."
#~ msgstr ""

#~ msgid "Specified RPC version, %(version)s, not supported by this endpoint."
#~ msgstr ""

#~ msgid ""
#~ "Specified RPC envelope version, %(version)s,"
#~ " not supported by this endpoint."
#~ msgstr ""

#~ msgid "Specified RPC version cap, %(version_cap)s, is too low"
#~ msgstr ""

#~ msgid "Returning exception %s to caller"
#~ msgstr ""

#~ msgid "Failed to process message ... skipping it."
#~ msgstr ""

#~ msgid "Failed to process message ... will requeue."
#~ msgstr ""

#~ msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
#~ msgstr ""

#~ msgid "Connected to AMQP server on %(hostname)s:%(port)d"
#~ msgstr ""

#~ msgid ""
#~ "Unable to connect to AMQP server "
#~ "on %(hostname)s:%(port)d after %(max_retries)d "
#~ "tries: %(err_str)s"
#~ msgstr ""

#~ msgid ""
#~ "AMQP server on %(hostname)s:%(port)d is "
#~ "unreachable: %(err_str)s. Trying again in "
#~ "%(sleep_time)d seconds."
#~ msgstr ""

#~ msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
#~ msgstr ""

#~ msgid "Timed out waiting for RPC response: %s"
#~ msgstr ""

#~ msgid "Failed to consume message from queue: %s"
#~ msgstr ""

#~ msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
#~ msgstr ""

#~ msgid "Invalid value for qpid_topology_version: %d"
#~ msgstr ""

#~ msgid "Failed to process message... skipping it."
#~ msgstr ""

#~ msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
#~ msgstr ""

#~ msgid "Connected to AMQP server on %s"
#~ msgstr ""

#~ msgid "Re-established AMQP queues"
#~ msgstr ""

#~ msgid "Error processing message.  Skipping it."
#~ msgstr ""

#~ msgid "JSON serialization failed."
#~ msgstr ""

#~ msgid "Deserializing: %s"
#~ msgstr ""

#~ msgid "Connecting to %(addr)s with %(type)s"
#~ msgstr ""

#~ msgid "-> Subscribed to %(subscribe)s"
#~ msgstr ""

#~ msgid "-> bind: %(bind)s"
#~ msgstr ""

#~ msgid "Could not open socket."
#~ msgstr ""

#~ msgid "Subscribing to %s"
#~ msgstr ""

#~ msgid "ZeroMQ socket could not be closed."
#~ msgstr ""

#~ msgid "You cannot recv on this socket."
#~ msgstr ""

#~ msgid "You cannot send on this socket."
#~ msgstr ""

#~ msgid "Running func with context: %s"
#~ msgstr ""

#~ msgid "Sending reply"
#~ msgstr ""

#~ msgid "RPC message did not include method."
#~ msgstr ""

#~ msgid "Registering reactor"
#~ msgstr ""

#~ msgid "In reactor registered"
#~ msgstr ""

#~ msgid "Consuming socket"
#~ msgstr ""

#~ msgid "Creating proxy for topic: %s"
#~ msgstr ""

#~ msgid "Topic contained dangerous characters."
#~ msgstr ""

#~ msgid "Topic socket file creation failed."
#~ msgstr ""

#~ msgid ""
#~ "Local per-topic backlog buffer full "
#~ "for topic %(topic)s. Dropping message."
#~ msgstr ""

#~ msgid "Required IPC directory does not exist at %s"
#~ msgstr ""

#~ msgid "Permission denied to IPC directory at %s"
#~ msgstr ""

#~ msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
#~ msgstr ""

#~ msgid "CONSUMER RECEIVED DATA: %s"
#~ msgstr ""

#~ msgid "ZMQ Envelope version unsupported or unknown."
#~ msgstr ""

#~ msgid "Skipping topic registration. Already registered."
#~ msgstr ""

#~ msgid "Consumer is a zmq.%s"
#~ msgstr ""

#~ msgid "Creating payload"
#~ msgstr ""

#~ msgid "Creating queue socket for reply waiter"
#~ msgstr ""

#~ msgid "Sending cast"
#~ msgstr ""

#~ msgid "Cast sent; Waiting reply"
#~ msgstr ""

#~ msgid "Received message: %s"
#~ msgstr ""

#~ msgid "Unpacking response"
#~ msgstr ""

#~ msgid "Unsupported or unknown ZMQ envelope returned."
#~ msgstr ""

#~ msgid "RPC Message Invalid."
#~ msgstr ""

#~ msgid "%(msg)s"
#~ msgstr ""

#~ msgid "Sending message(s) to: %s"
#~ msgstr ""

#~ msgid "No matchmaker results. Not casting."
#~ msgstr ""

#~ msgid "No match from matchmaker."
#~ msgstr ""

#~ msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
#~ msgstr ""

#~ msgid "Match not found by MatchMaker."
#~ msgstr ""

#~ msgid "Matchmaker does not implement registration or heartbeat."
#~ msgstr ""

#~ msgid "Matchmaker unregistered: %(key)s, %(host)s"
#~ msgstr ""

#~ msgid "Register before starting heartbeat."
#~ msgstr ""

#~ msgid "No key defining hosts for topic '%s', see ringfile"
#~ msgstr ""

#~ msgid "Creating Consumer connection for Service %s"
#~ msgstr ""

#~ msgid "FakeLdap initialize url=%s"
#~ msgstr ""

#~ msgid "FakeLdap bind dn=%s"
#~ msgstr ""

#~ msgid "FakeLdap bind fail: dn=%s not found"
#~ msgstr ""

#~ msgid "FakeLdap bind fail: password for dn=%s not found"
#~ msgstr ""

#~ msgid "FakeLdap bind fail: password for dn=%s does not match"
#~ msgstr ""

#~ msgid "FakeLdap add item: dn=%(dn)s, attrs=%(attrs)s"
#~ msgstr ""

#~ msgid "FakeLdap add item failed: dn=%s is already in store."
#~ msgstr ""

#~ msgid "FakeLdap delete item failed: dn=%s not found."
#~ msgstr ""

#~ msgid "FakeLdap modify item: dn=%(dn)s attrs=%(attrs)s"
#~ msgstr ""

#~ msgid "FakeLdap modify item failed: dn=%s not found."
#~ msgstr ""

#~ msgid "FakeLdap modify item failed: item has no attribute \"%s\" to delete"
#~ msgstr ""

#~ msgid ""
#~ "FakeLdap modify item failed: item has"
#~ " no attribute \"%(k)s\" with value "
#~ "\"%(v)s\" to delete"
#~ msgstr ""

#~ msgid "FakeLdap modify item failed: unknown command %s"
#~ msgstr ""

#~ msgid "modify_s action %s not implemented"
#~ msgstr ""

#~ msgid "FakeLdap search at dn=%(dn)s scope=%(scope)s query=%(query)s"
#~ msgstr ""

#~ msgid "FakeLdap search fail: dn not found for SCOPE_BASE"
#~ msgstr ""

#~ msgid "Search scope %s not implemented."
#~ msgstr ""

#~ msgid ""
#~ "kvs token backend is DEPRECATED. Use "
#~ "keystone.token.backends.sql or "
#~ "keystone.token.backend.memcache instead."
#~ msgstr ""

#~ msgid ""
#~ "Successful set of token-index-list "
#~ "for user-key \"%(user_key)s\", #%(count)d "
#~ "records"
#~ msgstr ""

#~ msgid ""
#~ "Failed to set token-index-list for"
#~ " user-key \"%(user_key)s\". Attempt "
#~ "%(cas_retry)d of %(cas_retry_max)d"
#~ msgstr ""

#~ msgid "Unable to add token user list"
#~ msgstr ""

#~ msgid "Unable to add token to revocation list."
#~ msgstr ""

